### ISSUE TITLE
duplicate private key error

### ISSUE THREAD

**Issue by Keyrxng** [ubiquity-os-marketplace/command-wallet#16]
It seems that there has been a duplicate private key error upon what I believe is a new contributor registering which seems very unlikely and needs debugged

_original [context](https://github.com/ubiquity/pay.ubq.fi/issues/281#issuecomment-2296727786)_

**Comment by 0x4007** [comment]
Check if Sybil!

**Comment by gentlementlegen** [comment]
I think this is a conflict between v1 and v2 when a new user registers a wallet. since both start at the same time, they both try to create a user so one of the two will fail. Maybe we should change the message by `The user already exists` as an info an not an error and keep the workflow going normally for the plugin.

**Comment by gentlementlegen** [comment]
This has been indirectly handled through https://github.com/ubiquity-os-marketplace/command-wallet/issues/28#issuecomment-2519730291
